image: gcc:10.2
pipelines:
  default:
    - step:
        name: Build and Test Baryon
        script:
          - wget https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh
          - bash Mambaforge-Linux-x86_64.sh -b
          - ~/mambaforge/bin/conda init
          - source ~/.bashrc
          - git clone git@bitbucket.org:gsitech/conda_channel.git
          - cd conda_channel
          - conda config --set custom_channels.gsi file://$PWD
          - cd ..
          - mamba env create -f environment.yml
          - conda activate baryon
          - DEBUG_MODE=true ./setup.sh --test
