image: gcc:10.2
pipelines:
  default:
    - step:
        name: Build and Test Baryon
        script:
          - wget https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh
          - bash Mambaforge-Linux-x86_64.sh -b
          - ~/mambaforge/bin/conda init
          - source ~/.bashrc
          - git clone git@bitbucket.org:gsitech/conda_channel.git
          - cd conda_channel
          - conda config --set custom_channels.gsi file://$PWD
          - cd ..
          - mamba env create -f environment.yml
          - conda activate baryon
          - git clone https://github.com/emil-e/rapidcheck.git
          - cd rapidcheck
          - git checkout 1505cbbce733bde3b78042cf2e9309c0b7f227a2
          - mkdir build
          - cd build
          - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DRC_ENABLE_GTEST=ON ..
          - make -j$(nproc)
          - make install
          - cd ../..
          - pip install git+ssh://git@bitbucket.org/gsitech/belex.git@773e68e1b9c70e16ec51a253b34c83972154bc80#egg=belex
          - pip install git+ssh://git@bitbucket.org/gsitech/belex-libs.git@3facd5241f2e8e12c3aa4afbd8d3e45751ccf63e#egg=belex-libs
          - git clone https://github.com/google/gtest-parallel.git
          - cd gtest-parallel
          - git checkout f4d65b555894b301699c7c3c52906f72ea052e83
          - ln -sv "$PWD/gtest-parallel" "$CONDA_PREFIX/bin/gtest-parallel"
          - cd ..
          - DEBUG_MODE=true ./setup.sh --prefix ~/local --enable-tests --num-cores $(nproc)
          - gtest-parallel --print_test_times ./build/test/test-baryon
