name: baryon
channels:
  - conda-forge
  - gsi
dependencies:
  - belex=1.0rc11
  - belex-libs=1.0rc11
  - rapidcheck=2023.01.13
  - cmake=3.25.2
  - gtest=1.12.1
  - gtest-parallel=2022.06.21
  - yaml-cpp=0.7.0
