/* By Dylon Edwards
 *
 * Copyright 2019 - 2023 GSI Technology, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the “Software”), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef __GSI__BARYON__CONSTANTS_H__
#define __GSI__BARYON__CONSTANTS_H__

#ifdef __cplusplus
extern "C" {
#endif

#define BARYON_NUM_SBS 24

#define BARYON_NUM_SECTIONS 16
#define BARYON_NUM_GROUPS 4

#define BARYON_NUM_L1_ROWS 384
#define BARYON_NUM_L2_ROWS 128

#define BARYON_MAX_SM_VALUE 0xFFFF
#define BARYON_MAX_RN_VALUE (BARYON_NUM_SBS - 1)
#define BARYON_MAX_RE_VALUE 0xFFFF00
#define BARYON_MAX_EWE_VALUE 0x2FF
#define BARYON_MAX_L1_VALUE ((1 << 13) - 1)
#define BARYON_MAX_L2_VALUE ((1 << 7) - 1)

#define BARYON_NUM_EWE_GROUPS 3
#define BARYON_NUM_VRS_PER_EWE_GROUP 8

#define BARYON_NUM_PLATS_PER_HALF_BANK 2048

#define BARYON_NUM_HALF_BANKS_PER_APC 8
#define BARYON_NUM_PLATS_PER_APC \
  (BARYON_NUM_PLATS_PER_HALF_BANK * BARYON_NUM_HALF_BANKS_PER_APC)

#define BARYON_NUM_APCS_PER_APUC 2
#define BARYON_NUM_HALF_BANKS_PER_APUC \
  (BARYON_NUM_HALF_BANKS_PER_APC * BARYON_NUM_APCS_PER_APUC)
#define BARYON_NUM_PLATS_PER_APUC \
  (BARYON_NUM_PLATS_PER_APC * BARYON_NUM_APCS_PER_APUC)

#define BARYON_NUM_APUCS_PER_APU 4
#define BARYON_NUM_APCS_PER_APU \
  (BARYON_NUM_APCS_PER_APUC * BARYON_NUM_APUCS_PER_APU)
#define BARYON_NUM_HALF_BANKS_PER_APU \
  (BARYON_NUM_HALF_BANKS_PER_APUC * BARYON_NUM_APCS_PER_APU)
#define BARYON_NUM_PLATS_PER_APU \
  (BARYON_NUM_PLATS_PER_APUC * BARYON_NUM_APUCS_PER_APU)

#define BARYON_NUM_SM_REGS 16
#define BARYON_NUM_RN_REGS 16
#define BARYON_NUM_RE_REGS 4
#define BARYON_NUM_EWE_REGS 4
#define BARYON_NUM_L1_REGS 4
#define BARYON_NUM_L2_REGS 1

#define BARYON_NUM_VR_SECTIONS BARYON_NUM_SECTIONS
#define BARYON_NUM_VR_PLATS BARYON_NUM_PLATS_PER_APUC

#define BARYON_NUM_RL_SECTIONS BARYON_NUM_VR_SECTIONS
#define BARYON_NUM_RL_PLATS BARYON_NUM_VR_PLATS

#define BARYON_NUM_RSP16_SECTIONS BARYON_NUM_SECTIONS
#define BARYON_NUM_RSP256_SECTIONS BARYON_NUM_SECTIONS
#define BARYON_NUM_RSP2K_SECTIONS BARYON_NUM_SECTIONS
#define BARYON_NUM_RSP32K_SECTIONS BARYON_NUM_SECTIONS

#define BARYON_NUM_RSP16_PLATS (BARYON_NUM_PLATS_PER_APUC / 16)
#define BARYON_NUM_RSP256_PLATS (BARYON_NUM_PLATS_PER_APUC / 256)
#define BARYON_NUM_RSP2K_PLATS (BARYON_NUM_PLATS_PER_APUC / 2048)

#define BARYON_NUM_LGL_PLATS (BARYON_NUM_PLATS_PER_HALF_BANK * 4)
#define BARYON_NUM_L2_PLATS BARYON_NUM_LGL_PLATS

#ifdef __cplusplus
}
#endif

#endif // __GSI__BARYON__CONSTANTS_H__
