#ifndef __LEPTON__CONSTANTS_H__
#define __LEPTON__CONSTANTS_H__

#define LEPTON_NUM_SBS 24

#define LEPTON_NUM_SECTIONS 16
#define LEPTON_NUM_GROUPS 4

#define LEPTON_NUM_L1_ROWS 384
#define LEPTON_NUM_L2_ROWS 128

#define LEPTON_MAX_SM_VALUE 0xFFFF
#define LEPTON_MAX_RN_VALUE (LEPTON_NUM_SBS - 1)
#define LEPTON_MAX_RE_VALUE 0xFFFF00
#define LEPTON_MAX_EWE_VALUE 0x2FF
#define LEPTON_MAX_L1_VALUE ((1 << 13) - 1)
#define LEPTON_MAX_L2_VALUE ((1 << 7) - 1)

#define LEPTON_NUM_PLATS_PER_HALF_BANK 2048

#define LEPTON_NUM_HALF_BANKS_PER_APC 8
#define LEPTON_NUM_PLATS_PER_APC \
  (LEPTON_NUM_PLATS_PER_HALF_BANK * LEPTON_NUM_HALF_BANKS_PER_APC)

#define LEPTON_NUM_APCS_PER_APUC 2
#define LEPTON_NUM_HALF_BANKS_PER_APUC \
  (LEPTON_NUM_HALF_BANKS_PER_APC * LEPTON_NUM_APCS_PER_APUC)
#define LEPTON_NUM_PLATS_PER_APUC \
  (LEPTON_NUM_PLATS_PER_APC * LEPTON_NUM_APCS_PER_APUC)

#define LEPTON_NUM_APUCS_PER_APU 4
#define LEPTON_NUM_APCS_PER_APU \
  (LEPTON_NUM_APCS_PER_APUC * LEPTON_NUM_APUCS_PER_APU)
#define LEPTON_NUM_HALF_BANKS_PER_APU \
  (LEPTON_NUM_HALF_BANKS_PER_APUC * LEPTON_NUM_APCS_PER_APU)
#define LEPTON_NUM_PLATS_PER_APU \
  (LEPTON_NUM_PLATS_PER_APUC * LEPTON_NUM_APUCS_PER_APU)

#define LEPTON_NUM_SM_REGS 16
#define LEPTON_NUM_RN_REGS 16
#define LEPTON_NUM_RE_REGS 4
#define LEPTON_NUM_EWE_REGS 4
#define LEPTON_NUM_L1_REGS 4
#define LEPTON_NUM_L2_REGS 1

#define LEPTON_NUM_VR_SECTIONS LEPTON_NUM_SECTIONS
#define LEPTON_NUM_VR_PLATS LEPTON_NUM_PLATS_PER_APUC

#define LEPTON_NUM_RL_SECTIONS LEPTON_NUM_VR_SECTIONS
#define LEPTON_NUM_RL_PLATS LEPTON_NUM_VR_PLATS

#define LEPTON_NUM_RSP16_SECTIONS LEPTON_NUM_SECTIONS
#define LEPTON_NUM_RSP256_SECTIONS LEPTON_NUM_SECTIONS
#define LEPTON_NUM_RSP2K_SECTIONS LEPTON_NUM_SECTIONS
#define LEPTON_NUM_RSP32K_SECTIONS LEPTON_NUM_SECTIONS

#define LEPTON_NUM_RSP16_PLATS (LEPTON_NUM_PLATS_PER_APUC / 16)
#define LEPTON_NUM_RSP256_PLATS (LEPTON_NUM_PLATS_PER_APUC / 256)
#define LEPTON_NUM_RSP2K_PLATS (LEPTON_NUM_PLATS_PER_APUC / 2048)
#define LEPTON_NUM_RSP32K_PLATS (LEPTON_NUM_PLATS_PER_APUC / 32768)

#define LEPTON_NUM_LGL_PLATS (LEPTON_NUM_PLATS_PER_HALF_BANK * 4)
#define LEPTON_NUM_L2_PLATS LEPTON_NUM_LGL_PLATS

#endif // __LEPTON__CONSTANTS_H__
